apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secretName" . }}
type: Opaque
data:
  aws_access_key_id: {{ .Values.bucket.aws_access_key_id | b64enc }}
  aws_secret_access_key: {{ .Values.bucket.aws_secret_access_key | b64enc }}
  user: {{ .Values.database.user | b64enc }}
  password: {{ .Values.database.password | b64enc }}
  {{- if .Values.notify.enabled }}
  channel: {{ .Values.notify.channel | b64enc }}
  webhookUrl: {{ .Values.notify.webhookUrl | b64enc }}
  {{- end }}
  my.cnf: {{ printf "[client]\nuser = %s\npassword = %s\nhost = %s\n" .Values.database.user .Values.database.password .Values.database.host | b64enc}}
